DELIMITER $$
DROP PROCEDURE IF EXISTS `create_db`;
CREATE DEFINER=`root`@`localhost` PROCEDURE `create_db`(IN  `dbName_in` VARCHAR(25))
BEGIN
	DECLARE SQLStmt TEXT;
	SET @SQLStmt = CONCAT('CREATE DATABASE ', dbName_in, ' CHARACTER SET utf8');
	PREPARE Stmt FROM @SQLStmt;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
  
	-- CREATE DATABASE dbName_in CHARACTER SET utf8;
    
END$$
DELIMITER ;

