ALTER TABLE configuration ADD category ENUM('BASIC','COURSE_APPLICATION') NULL DEFAULT 'BASIC';
ALTER TABLE configuration ADD spec ENUM('0','1') NOT NULL DEFAULT '0';

UPDATE configuration SET category='COURSE_APPLICATION' WHERE name IN (
'COURSE_APPLICATION_ALLOWED'
,'COURSE_APPL_SEL_REQ'
,'HEALTH_AGREEMENT'
,'PERSONAL_DATA_PROCESS_AGREEMENT'
,'CLUB_RULES_AGREEMENT'
,'COURSE_APPL_EMAIL_SPEC_TEXT'
,'ALLOW_COURSE_APPL_NOT_VALID_ADDRESS');